### PR TITLE
Make FBLPromise.pendingObjects access threadsafe

### LINKED ISSUE #141: SIGABRT due to malloc errors when using Promises from swift?
We're experiencing some strange/confusing crashes and trying to figure out how to investigate further. Have you seen or heard of anything like this previously?

```
OS Version: tvOS 13.4 (17L256)
Report Version: 104

Exception Type: Unknown (SIGABRT)
Crashed Thread: 29

Application Specific Information:
Channels > Channels(2107,0x16d913000) malloc: *** error for object 0x282ffd2c0: pointer being freed was not allocated


Thread 29 Crashed:
0   libsystem_kernel.dylib          0x35486ed88         __pthread_kill
1   libsystem_pthread.dylib         0x34172d69c         pthread_kill
2   libsystem_c.dylib               0x354e78580         abort
3   libsystem_malloc.dylib          0x366857d30         malloc_vreport
4   libsystem_malloc.dylib          0x366857ee8         malloc_report
5   libsystem_malloc.dylib          0x36684d21c         free
6   CoreFoundation                  0x3427686f0         __rehashs
7   CoreFoundation                  0x3426c0314         -[__NSSetM addObject:]
8   Promises                        0x102e5b394         Promise.then (Promise+Then.swift:101)
```

### PR DESCRIPTION
**Pull request by eric**
Swift uses the NSMutableSet to hold on to references of Swift promises but the
modifications must be synchronized.

This is intended to fix #141.

### CODE REVIEW

**Comment by eric** [comment]
@googlebot I signed it!

File: Sources/FBLPromises/FBLPromise.m [hunk 1]
```diff
@@ -202,6 +202,16 @@ - (NSMutableSet *__nullable)pendingObjects {
   }
 }
 
+- (void)addToPendingObjects:(id)object {
```
Comment (shoumikhin) [inline Sources/FBLPromises/FBLPromise.m:205]: Nit: Let's name it `addPendingObject`

File: Sources/FBLPromises/FBLPromise.m [hunk 2]
```diff
@@ -202,6 +202,16 @@ - (NSMutableSet *__nullable)pendingObjects {
...
+  NSMutableSet *set = [self pendingObjects];
+
+  if (set) {
+    @synchronized(set) {
+      [set addObject:object];
```
Comment (shoumikhin) [inline Sources/FBLPromises/FBLPromise.m:210]: Can you please move the set creation logic over here from `pendingObjects` getter?

File: Sources/FBLPromises/include/FBLPromise+Testing.h [hunk 3]
```diff
@@ -46,6 +46,11 @@ FOUNDATION_EXTERN BOOL FBLWaitForPromisesWithTimeout(NSTimeInterval timeout) NS_
  */
 @property(nonatomic, readonly, nullable) NSMutableSet *pendingObjects NS_REFINED_FOR_SWIFT;
 
+/**
+ Add an object to the set of pending objects to keep strongly while the promise is pending.
+ */
+- (void)addToPendingObjects:(id)object NS_REFINED_FOR_SWIFT;
```
Comment (shoumikhin) [inline Sources/FBLPromises/include/FBLPromise+Testing.h:52]: Doesn't seem we need that readonly property above anymore, this method should be sufficient.
Can you remove that please?

File: Sources/FBLPromises/FBLPromise.m (hunk 2 above)
Comment (eric) [reply Sources/FBLPromises/FBLPromise.m:210]: sure

File: Sources/FBLPromises/include/FBLPromise+Testing.h (hunk 3 above)
Comment (eric) [reply Sources/FBLPromises/include/FBLPromise+Testing.h]: Sure. The only reason why it was needed is that it's used in a bunch of places in tests to confirm that the pending objects are empty.

**Comment by eric** [comment]
When I try to move it under `FBLPromise+Testing.h` it gives me a warning that it wants me to implement it in `FBLPromise+Testing.m`. Should I do that?

File: Sources/FBLPromises/FBLPromise.m [hunk 4]
```diff
@@ -191,23 +191,13 @@ - (NSError *__nullable)error {
   }
 }
 
-- (NSMutableSet *__nullable)pendingObjects {
+- (void)__addPendingObject:(id)object {
```
Comment (shoumikhin) [inline Sources/FBLPromises/FBLPromise.m:194]: Nit:

```suggestion
- (void)addPendingObject:(id)object {
  NSParameterAssert(object);

```

File: Sources/FBLPromises/include/FBLPromise.h [hunk 5]
```diff
@@ -55,14 +55,13 @@ NS_ASSUME_NONNULL_BEGIN
...
 - (void)reject:(NSError *)error NS_REFINED_FOR_SWIFT;
 
-+ (instancetype)new NS_UNAVAILABLE;
-- (instancetype)init NS_UNAVAILABLE;
-
 /**
  Add an object to the set of pending objects to keep strongly while the promise is pending.
  */
-- (void)addToPendingObjects:(id)object NS_REFINED_FOR_SWIFT;
+- (void)__addPendingObject:(id)object;
```
Comment (shoumikhin) [inline Sources/FBLPromises/include/FBLPromise.h:61]: Let's move it under an extension just to keep it separate from the rest of public APIs

```
@interface FBLPromise<Value>()

/**
 Adds an object to the set of pending objects to keep strongly while the promise is pending.
 Used by the Swift wrappers to keep them alive until the underlying ObjC promise is resolved.

 @param object An object to add.
 */
- (void)addPendingObject:(id)object NS_REFINED_FOR_SWIFT;

@end
```

**Comment by eric** [comment]
I've updated based on comments.

**Comment by eric** [comment]
Huh... the tests were passing for me. I wonder what’s going on.

**Comment by shoumikhin** [comment]
You can find the details on [Travis CI](https://travis-ci.org/github/google/promises/builds/687156851)

**Comment by eric** [comment]
I realized I was only running the Swift tests and not Objective-C ones. This should be better now.

**Comment by eric** [comment]
Haha. Would you rather I get rid of the checks or just keep them?

**Comment by shoumikhin** [comment]
Feel free to remove them as the property is already gone.

**Comment by eric** [comment]
I've removed it. It should be ready to merge.
